config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'about', to: "welcome#about"
  get 'servicios', to: "welcome#servicios"
  get 'contacto', to: "welcome#contacto"
  get 'valores', to: "welcome#valores"
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@welcome = 'Daniel'
  end
  def about

  end
  def servicio
  end
  def contacto
  end
  def valores
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SRD</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'icono.png' %>
  </head>

  <body class="bg-success">
  	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  		<div class=col-2">
	  		<%= image_tag("Logo.png", class: "rounded-circle embed-responsive w-50") %> 
	  	</div>
	 	<div class="col-8">
	  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    	<span class="navbar-toggler-icon"></span>
	  		</button>
	  		<div class="collapse navbar-collapse" id="navbarNav">
	    	<ul class="navbar-nav">
		    	<li>
		    		<%= link_to "Inicio", root_path, class: "navbar-brand" %>
		    	</li>	
		      	<li class="nav-item active">
		        	<%= link_to "About", about_path, class: "navbar-brand" %>
		      	</li>
		      	<li class="nav-item active">
		       		<%= link_to "Servicios", servicios_path, class: "navbar-brand" %>
		     	</li>
		      	<li class="nav-item active">
		        	<%= link_to "Contacto", contacto_path, class: "navbar-brand" %>
		      	</li>
		      	<li class="nav-item active">
		        	<%= link_to "Valores", valores_path, class: "navbar-brand" %>
		      	</li>
	   		</ul>
	  	</div>
	  </div>
	  <div class=col-2">
	  		<%= image_tag("Logo_c.png", class: "rounded-circle embed-responsive w-50") %> 
	  	</div>
	</nav>
<br />
  	<div>
  		<%= yield %>
  	</div>
    
  </body>
</html>

app/views/welcome/about.html.erb
<div class="container">
<div class="row">
	<div class="col-md-12" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="left">Conoce sobre nosotros</h3>
        </div>  
        <p align="justify">
            Servicio a domicilio de recolección, es una empresa integradora de servicios que benefician a la comunidad y procurando un medio ambiente más limpio.
        </p>
        <p align="justify">
		Contamos con las herramientas que le permiten actuar a favor del medio ambiente y contribuimos al bienestar económico de nuestros colaboradores al brindarles una forma de laborar.
        </p>
        <p align="justify">
		Misión
        </p>
		<p>
		SDR, es un servicio de integración que permite conectar al cliente con los proveedores, que le permitirán hacer la disposición final de los residuos que se generen en su domicilio o comercio y que por alguna razón, las empresas encargadas no le prestan el servicio, ajustándose a las necesidades de tiempo.
		</p>
    
        <p align="justify">
		Visión
        </p>
        <p align="justify">
		SDR, será para el 2020 la empresa líder en integración de servicios de recolección a domicilio y disposición final de desechos domiciliarios y comerciales orgánico  e inorgánico.
		</p> 
	</div>
    </div>
</div>
</div>

app/views/welcome/contacto.html.erb
<div class="container">
<div class="row">
	<div class="col-md-12" align="center">
    <div class="col-md-4" align="center">&nbsp;</div>
    <div class="col-md-4" align="center">
   		<div class="panel panel-primary">
    		<div class="panel-heading">
        		<h3 class="panel-title" align="left">Comunicate con nosotros</h3>
        	</div>
            <div class="input-group input-group-sm">
            <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-paperclip"></i></span>
            contacto@dominio.com.co
          	</div>
            <div class="input-group input-group-sm">
            <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-phone"></i></span>
            (0057) 333 555 55 55
          	</div>
            <div class="input-group input-group-sm">
            <span class="input-group-addon" id="sizing-addon1"><i class="glyphicon glyphicon-phone-alt"></i></span>
            (0057)(1) 555 55 55
          	</div>
    	</div>        
	</div>
    <div class="col-md-4" align="center">&nbsp;</div>
    </div>
</div>
<div class="row">
	<div class="col-md-12" align="center">
   		<div class="panel panel-primary">
    		<div class="panel-heading">
        		<h3 class="panel-title" align="left">Encuentranos aquí</h3>
        	</div>
        	<%= image_tag("mapa.png") %> 
    	</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12" align="center">
    <div class="col-md-4" align="center">&nbsp;</div>
    <div class="col-md-4" align="center">
		<div class="panel panel-primary">
    	<div class="panel-heading">
        	<h3 class="panel-title" align="left">Deja un comentario </h3>
        </div>
          <form action="#" method="post" id="commentform">
            <p>
              <label for="comment">Comentario</label>
              <textarea id="comment" name="comment" cols="25" rows="8" maxlength="65525" required="required"></textarea>
            </p>
            <p>
              <label for="author">Nombre *</label>
              <input id="author" name="author" value="" size="30" maxlength="245" required="required" type="text" />
            </p>
            <p>
              <label for="email">Correo *</label>
              <input id="email" name="email" value="" size="30" maxlength="100" aria-describedby="email-notes" required="required" type="text" />
            </p>
          </form>
          <p> </p>
          <p align="left">
            <label>
              <input value="1" name="comment_subscribe" type="checkbox" />
              También suscribirme al newsletter mensual.</label>
          </p>
          <p align="left">
            <input name="subscribe_comments" id="subscribe_comments" value="subscribe" type="checkbox" />
            <label id="subscribe-label" for="subscribe_comments">Recibir un email de respuesta.</label>
          </p>
          <p align="center"><input type="submit" class="btn btn-primary col-md-6" name="enviar" id="enviar" value="Enviar"></p>
		</div>
		</div>
    <div class="col-md-4" align="center">&nbsp;</div>      
    </div>
</div>
</div>

app/views/welcome/index.html.erb
<div class="container">
<div class="row">
	<div class="col-md-12" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="left">Últimas noticias</h3>
          </div>  
          <div class="col-md-6">
            <h4>Cambios en esquemas de recoleccón</h4>
            <p align="justify">
              Desde el pasado lunes 12 de febrero Bogotá se dividió en 5 áreas de servicio exclusivo para adelantar las labores de recolección de residuos.
            </p>
            <p align="justify">
              Los nuevos cinco operadores a los que les fue adjudicada la licitación tienen a su cargo diferentes localidades para adelantar labores.
              <br />
              Área de servicio exclusivo 1: Fue adjudicada a Promoambiental. Tiene a su cargo las localidades de Usaquén, Chapinero, Santa Fe, San Cristóbal, Usme  y Sumapaz.
            </p>
            <p align="justify">
              El centro de atención al usuario de este operador se encuentra ubicado en la Transversal 4 N 51ª 25 y presta atención en un horario de 7 de la mañana a 5 de la tarde de lunes a viernes y los sábados de 9 de la mañana a 1 de la tarde. La línea de atención es 9261923
            </p>
            <p align="right">Leer completo</p>
          </div>
          <div class="col-md-6">
            <h4>Recomendaciones del mes</h4>
            <p align="justify">
              En la última década hemos visto un aumento en la conciencia social al respecto del medio ambiente. Organizaciones sin fines de lucro tienen más presencia en el mundo y cada vez existen más leyes que apoyan a mejorar la situación ambiental.
            </p>
            <p align="justify">
              También nosotros podemos apoyar aunque sea empezando por algo pequeño. A continuación una serie de consejos para cuidar y proteger el medio ambiente:
            </p>
            <p align="justify">
              <ul><li>Aprovechemos al máximo la luz, con los cambios de horario nos ayuda también a conservar más energía.</li></ul>
            </p>
            <p align="right">Leer completo</p>
          </div>
    </div>
	</div>
</div>
<div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="left">Lecturas recomendadas</h3>
          </div>  

  </div>


</div>

app/views/welcome/servicios.html.erb
<div class="container">
<div class="row">
	<div class="col-md-12" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="left">Conoce sobre nosotros</h3>
        </div>  
        <p align="justify">
		<ul align="justify">
        	<li align="justify">
			<strong>Recolección a domicilio:</strong> permite que el usuario establezca la mejor opción de recolección de sus residuos orgánicos.
			</li>
			<li align="justify">
			<strong>Recolección a domicilio:</strong> permite que el usuario establezca la mejor opción de recolección de sus residuos inorgánicos, producto de construcción o actividades no industriales.
			</li>
			<li align="justify">
			<strong>Barrido de salones y espacios no públicos:</strong> limpieza detallada en general mediante la utilización de herramientas manuales. Adicionalmente, se realiza la eliminación de residuos sólidos acumulados.
			</li>
			<li align="justify">
			<strong>Transferencia:</strong> teniendo en cuenta que hoy en día algunos rellenos sanitarios se encuentran en lugares alejados de los centros urbanos, surge la necesidad de un punto de  almacenamiento temporal de los residuos, garantizando que no se genere contaminación
			</li>
			<li align="justify">
			<strong>Reciclaje:</strong> el aprovechamiento y valorización de los residuos es un compromiso de corresponsabilidad tanto de las autoridades ambientales, de los entes territoriales y de la comunidad. 
			</li>
		</ul>
        </p>
    </div>  
    
      
	</div>
</div>
</div>

app/views/welcome/valores.html.erb
<div class="container">
<div class="row">
	<div class="col-md-12" align="center">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title" align="left">Conoce sobre nuestros valores</h3>
        </div>  
        <p align="justify">
		<ul align="justify">
        	<li align="justify">
			<strong>Compromiso con nuestros usuarios:</strong> orienta las actividades hacia todos los usuarios, satisfaciendo sus necesidades y expectativas, ofreciendo un servicio integral confiable.
			</li>
			<li align="justify">
			<strong>Respeto a la legalidad:</strong> todas las actividades y acciones desde la plataforma, se inspiran en el respeto a las personas, culturas, creencias y valores.
			</li>
			<li align="justify">
			<strong>Trabajo en equipo:</strong> todos los colaboradores trabajarán mediante un ambiente de integridad, colaboración y apoyo entre usuarios.
			</li>
			<li align="justify">
			<strong>Ética:</strong> esperamos y confiamos en el buen comportamiento y actuar de todos los usuarios.
			</li>
			<li align="justify">
			<strong>Beneficio:</strong> para asegurar un desarrollo sostenible, adecuado y permanente, la plataforma debe lograr un buen índice de rentabilidad que genere mayor confianza a nuestros socios, proveedores, colaboradores y al estado.
			</li>
			<li align="justify">
			<strong>Responsabilidad Social:</strong> la plataforma contribuirá en la medida de sus recursos en el desarrollo del sector y del medio ambiente.
			</li>
		</ul>
        </p>
    </div>  
    
      
	</div>
</div>
</div>